### ISSUE TITLE
Quantité négative généère une erreur du service

### ISSUE THREAD

**Issue by HenriMichelonEsimed** [abonnet-pro/JS-Front#1]
Lors de la saisie d'une quantité négative pour l'ajout d'un article une erreur du service est affichée au lieu d'un message de validation :
![image](https://user-images.githubusercontent.com/40261437/114025105-11133880-9875-11eb-96e2-c5f62cd52725.png)

**Comment by abonnet-pro** [comment]
La correction est poussée sur le dépot
